version: "3"
services:
  api:
    container_name: nomnom
    build: ./packages/nomnom-server-api
    restart: always
    links:
      - db
    ports:
      - "4000:4000"
    environment:
      - PG_HOST=db
  db:
    container_name: nomnom-postgres
    build: ./db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=nomnom
