-- MySQL Script generated by MySQL Workbench
-- Sun May  7 14:30:28 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema nomnom
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS  "nomnom"  ;

-- -----------------------------------------------------
-- Table "nomnom"."User"
-- -----------------------------------------------------
CREATE TABLE "nomnom"."User" (
  "id" UUID NOT NULL,
  "email" VARCHAR(150) NOT NULL,
  "name" VARCHAR(150) NULL,
  "avatarUrl" VARCHAR(200) NULL,
  PRIMARY KEY ("id"),
  UNIQUE("email"));

-- -----------------------------------------------------
-- Table "nomnom"."Entry"
-- -----------------------------------------------------
CREATE TABLE "nomnom"."Entry" (
  "id" UUID NOT NULL,
  "url" VARCHAR(200) NULL,
  "title" VARCHAR(200) NULL,
  "originalContent" TEXT NULL,
  "creationDate" TIMESTAMP NULL,
  "publicationDate" TIMESTAMP NULL,
  "author" VARCHAR(200) NULL,
  "excerpt" TEXT NULL,
  "content" TEXT NULL,
  "imageUrl" VARCHAR(200) NULL,
  "duration" INT NULL,
  PRIMARY KEY ("id"),
  UNIQUE("url")
  );


-- -----------------------------------------------------
-- Table "nomnom"."Feed"
-- -----------------------------------------------------
CREATE TYPE "nomnom"."FeedType" AS ENUM ('RSS');
CREATE TABLE "nomnom"."Feed" (
  "id" UUID NOT NULL,
  "uri" VARCHAR(200) NULL,
  "type" "nomnom"."FeedType" NULL,
  "creationDate" TIMESTAMP NULL,
  "lastFetchedDate" TIMESTAMP NULL,
  PRIMARY KEY ("id"),
  UNIQUE("uri"));


-- -----------------------------------------------------
-- Table "nomnom"."UserEntry"
-- -----------------------------------------------------
CREATE TYPE "nomnom"."UserEntryStatus" AS ENUM ('NEW', 'LATER', 'FAVORITE', 'ARCHIVED');
CREATE TABLE  "nomnom"."UserEntry" (
  "id" UUID NOT NULL,
  "UserId" UUID NOT NULL,
  "EntryId" UUID NOT NULL,
  "creationDate" TIMESTAMP NULL,
  "lastUpdateDate" TIMESTAMP NULL,
  "progress" INT NULL,
  "status" "nomnom"."UserEntryStatus" NULL,
  "tags" TEXT[] NULL,
  PRIMARY KEY ("UserId", "EntryId"),
  UNIQUE("id"),
  CONSTRAINT "fk_UserEntry_User"
    FOREIGN KEY ("UserId")
    REFERENCES "nomnom"."User" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "fk_UserEntry_Entry"
    FOREIGN KEY ("EntryId")
    REFERENCES "nomnom"."Entry" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table "nomnom"."UserFeed"
-- -----------------------------------------------------
CREATE TABLE  "nomnom"."UserFeed" (
  "id" UUID NOT NULL,
  "UserId" UUID NOT NULL,
  "FeedId" UUID NOT NULL,
  "creationDate" TIMESTAMP NULL,
  "name" TEXT NOT NULL,
  "enabled" BOOLEAN  NOT NULL DEFAULT TRUE,
  PRIMARY KEY ("UserId", "FeedId"),
  UNIQUE("id"),
  CONSTRAINT "fk_UserFeed_User"
    FOREIGN KEY ("UserId")
    REFERENCES "nomnom"."User" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "fk_UserFeed_Feed"
    FOREIGN KEY ("FeedId")
    REFERENCES "nomnom"."Feed" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
